/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package run;

/**
 *
 * @author Felipe
 */
public class Instrucciones extends javax.swing.JFrame {

    /**
     * Creates new form Instrucciones
     */
    public Instrucciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 410));
        setMinimumSize(new java.awt.Dimension(400, 410));
        setPreferredSize(new java.awt.Dimension(400, 410));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("con el fin de dar prioridad a ciertas operaciones, para generar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 90, 360, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puedes generar un automata finito determinisco a partir de una");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 360, 20);

        jButton1.setText("Ok!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 340, 49, 32);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("union se usa \"|\", para el kleene star \"*\" y para clausura que no");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 50, 360, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("expresion regular. Para la concatenacion se usa el \".\", para la ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 30, 360, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("incluye la secuencia nula \"+\", se puede parentizar expresiones");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 360, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" un buen automata evite el uso de espacios. ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 110, 360, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clickeando en \"Generar programa\" genera el programa para");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 130, 360, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("el automata en cuestion, este se escribira en un archivo llamado");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 150, 370, 16);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("\"Programa.java\" que se creara si es la primera vez que realiza la");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 170, 370, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("accion, de lo contrario se sobreescribira, este archivo puede ser");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 190, 370, 16);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ejecutado y testeado con una hilera compuesta por los simbolos");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 210, 370, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("del lenguaje reconocido por el automata, se imprimira en consola");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 230, 370, 16);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("el estado final de la hilera y si dicha hilera es aceptada(true) o por ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 250, 380, 16);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("el contrario es rechazada(false).");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 270, 360, 16);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Para automatas muy grandes se puede visualizar los estados");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 290, 370, 16);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("clickeando sobre ellos en la matriz de estados y transiciones.");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 310, 350, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fonndo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instrucciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
